version: '3.1'

services:
  dbd:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_VERSION: '5.7.24'
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./databases:/var/lib/mysql
    ports:
      - "3307:3306"
    restart: always

  app:
    build: ./
    image: arnio/drupal:1.0
    environment:
      TZ: Europe/Kiev
    ports:
      - "8001:80"
    links:
      - dbd:dbd
    depends_on:
      - dbd  
    restart: always